# Theory of Complex Vector Spaces
Complex vector spaces extend the idea of real vector spaces by allowing vectors to have complex numbers as their components. In these spaces, vectors can be added together and multiplied by complex scalars to produce new vectors. Key operations in complex vector spaces include vector addition, scalar multiplication, vector negation, and complex conjugation.

# Creating complex column vectors

In [2]:
%pip install numpy 

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 4.2 MB/s eta 0:00:03
   ---- ----------------------------------- 1.3/12.6 MB 4.0 MB/s eta 0:00:03
   ------ --------------------------------- 2.1/12.6 MB 3.8 MB/s eta 0:00:03
   --------- ------------------------------ 2.9/12.6 MB 3.7 MB/s eta 0:00:03
   ----------- ---------------------------- 3.7/12.6 MB 3.6 MB/s eta 0:00:03
   -------------- ------------------------- 4.5/12.6 MB 3.7 MB/s eta 0:00:03
   ----------------- ---------------------- 5.5/12.6 MB 3.9 MB/s eta 0:00:02
   ------------------- -------------------- 6.3/12.6 MB 3.8 MB/s eta 0:00:02
   ---------------------- ----------------- 7.1/12.6 MB 3.8 MB/s eta 0:00:02
   ------------------------ --------------- 7.9/12.6 MB 3.9 MB/s eta 0:00:02
   --------------------------- ------------ 8.7/12.6 MB 3.8 MB/s eta 0:00:02
   ----------------------------- ---------- 9.2/12.6 MB 3.8 MB/s eta 0:00:01
   ---

In [3]:
import numpy as np

# Define a 2x2 square matrix
matrix = np.array([[2, 3],
                   [1, 4]])

# Define a vector of size 2
vector = np.array([5, 6])

# Multiply the matrix by the vector
result = np.dot(matrix, vector)

# Display the result
print("Matrix:\n", matrix)
print("\nVector:\n", vector)
print("\nResult of multiplication:\n", result)


Matrix:
 [[2 3]
 [1 4]]

Vector:
 [5 6]

Result of multiplication:
 [28 29]


## Manipulating Complex Column Vectors using NumPy
Here we demonstrate how to manipulate complex column vectors using NumPy, including operations like sum, negation, multiplication by a scalar, transpose, adjunct, and conjugate.

In [4]:

import numpy as np

# Define two complex column vectors
v1 = np.array([[2+3j], [5-4j], [1+1j]])
v2 = np.array([[1-1j], [3+2j], [4-4j]])

# Sum
sum_v = v1 + v2

# Negation
neg_v1 = -v1

# Multiplication by a scalar
scalar = 2 + 1j
mult_v1 = v1 * scalar

# Transpose
transpose_v1 = v1.T

# Adjunct (Conjugate transpose)
adjunct_v1 = v1.T.conj()

# Conjugate
conjugate_v1 = np.conjugate(v1)

(sum_v, neg_v1, mult_v1, transpose_v1, adjunct_v1, conjugate_v1)


(array([[3.+2.j],
        [8.-2.j],
        [5.-3.j]]),
 array([[-2.-3.j],
        [-5.+4.j],
        [-1.-1.j]]),
 array([[ 1.+8.j],
        [14.-3.j],
        [ 1.+3.j]]),
 array([[2.+3.j, 5.-4.j, 1.+1.j]]),
 array([[2.-3.j, 5.+4.j, 1.-1.j]]),
 array([[2.-3.j],
        [5.+4.j],
        [1.-1.j]]))

# Theory of Vector Spaces using Matrices
In the context of matrices, vector spaces can be defined where each vector is a matrix of a particular size. Operations on these matrix-vector spaces include matrix addition, scalar multiplication, matrix negation, transpose, adjunct, and conjugate. In this section, we focus on square matrices of size 3x3.

## Manipulating Square Matrices using NumPy
Examples of how to manipulate 3x3 square matrices using NumPy, showing operations such as sum, negation, multiplication by a scalar, conjugate, transpose, and adjunct.

In [5]:

# Define two 3x3 complex matrices
m1 = np.array([[2+3j, 4-1j, 0], 
               [1+1j, 3+3j, 5], 
               [4, 6-2j, 1-1j]])
m2 = np.array([[1, 2+1j, 3-3j], 
               [0, -1+2j, 1-2j], 
               [3+3j, 2, 4+4j]])

# Sum
sum_m = m1 + m2

# Negation
neg_m1 = -m1

# Multiplication by a scalar
scalar = 0.5 + 0.5j
mult_m1 = m1 * scalar

# Conjugate
conjugate_m1 = np.conjugate(m1)

# Transpose
transpose_m1 = m1.T

# Adjunct (Conjugate transpose)
adjunct_m1 = m1.T.conj()

(sum_m, neg_m1, mult_m1, conjugate_m1, transpose_m1, adjunct_m1)


(array([[3.+3.j, 6.+0.j, 3.-3.j],
        [1.+1.j, 2.+5.j, 6.-2.j],
        [7.+3.j, 8.-2.j, 5.+3.j]]),
 array([[-2.-3.j, -4.+1.j, -0.-0.j],
        [-1.-1.j, -3.-3.j, -5.-0.j],
        [-4.-0.j, -6.+2.j, -1.+1.j]]),
 array([[-0.5+2.5j,  2.5+1.5j,  0. +0.j ],
        [ 0. +1.j ,  0. +3.j ,  2.5+2.5j],
        [ 2. +2.j ,  4. +2.j ,  1. +0.j ]]),
 array([[2.-3.j, 4.+1.j, 0.-0.j],
        [1.-1.j, 3.-3.j, 5.-0.j],
        [4.-0.j, 6.+2.j, 1.+1.j]]),
 array([[2.+3.j, 1.+1.j, 4.+0.j],
        [4.-1.j, 3.+3.j, 6.-2.j],
        [0.+0.j, 5.+0.j, 1.-1.j]]),
 array([[2.-3.j, 1.-1.j, 4.-0.j],
        [4.+1.j, 3.-3.j, 6.+2.j],
        [0.-0.j, 5.-0.j, 1.+1.j]]))

## Checking the Dimension of a Matrix
We can check the dimension of a matrix using the `.shape` attribute.

In [6]:
# Checking the dimension of matrix1
m1.shape

(3, 3)

## Action of a Matrix on a Vector
Finally, examples of how to use Python to multiply a 3x3 square matrix by a 3x1 column vector.

In [7]:

# Multiplying a 3x3 matrix by a 3x1 vector
result = np.dot(m1, v1)
result


array([[11. -9.j],
       [31.+13.j],
       [32.-22.j]])

# Exercises on Complex Vectors and Matrices with Concrete Cases

This set of exercises focuses on operations with complex column vectors and complex square matrices, including concrete cases with vectors and matrices written in LaTeX format.

## Complex Column Vector Operations

### Exercise 1: Sum of Two Complex Vectors
Given two complex vectors 
$ v1 = \begin{bmatrix} 1 + 2i \\ 3 - i \end{bmatrix} $ 
and 
$ v2 = \begin{bmatrix} 2 - i \\ 4 + 2i \end{bmatrix} $, 
find their sum.

### Exercise 2: Negation of a Complex Vector
Given a complex vector 
$ v = \begin{bmatrix} 2 + 3i \\ 1 - 2i \end{bmatrix} $, 
find its negation.

### Exercise 3: Multiplication of a Complex Vector by a Scalar
Multiply the complex vector 
$ v = \begin{bmatrix} 1 - i \\ 2 + 2i \end{bmatrix} $ 
by the complex scalar $$ 3 + i $$.

### Exercise 4: Transpose of a Complex Vector
Find the transpose of the complex vector 
$ v = \begin{bmatrix} 2 - i \\ 3 + 4i \end{bmatrix} $.

### Exercise 5: Conjugate of a Complex Vector
Compute the conjugate of the complex vector 
$ v = \begin{bmatrix} 1 + i \\ 2 - 3i \end{bmatrix} $.

### Exercise 6: Adjunct (Conjugate Transpose) of a Complex Vector
Find the adjunct (or conjugate transpose) of the complex vector 
$ v = \begin{bmatrix} 1 - 2i \\ 3 + i \end{bmatrix} $.

## Complex Square Matrix Operations

### Exercise 7: Sum of Two Complex Matrices
Given two complex matrices 
$ m1 = \begin{bmatrix} 1 + i & 2 - i \\ 3 + 2i & 4 \end{bmatrix} $
and 
$ m2 = \begin{bmatrix} 2 - 3i & 1 \\ i & 2 + 2i \end{bmatrix} $, 
calculate their sum.

### Exercise 8: Negation of a Complex Matrix
Find the negation of the complex matrix 
$ m = \begin{bmatrix} 2 + i & 3 \\ 1 - i & 2 + 2i \end{bmatrix} $.

### Exercise 9: Multiplication of a Complex Matrix by a Scalar
Multiply the complex matrix 
$ m = \begin{bmatrix} 1 - i & 2 \\ 3 + i & 4 - 2i \end{bmatrix} $ 
by the complex scalar $$ 2 + 3i $$.

### Exercise 10: Conjugate of a Complex Matrix
Compute the conjugate of the complex matrix 
$ m = \begin{bmatrix} 1 + i & 2 \\ 3 - i & 4 + 2i \end{bmatrix} $.

### Exercise 11: Transpose of a Complex Matrix
Find the transpose of the complex matrix 
$ m = \begin{bmatrix} 1 - i & 2 + 2i \\ 3 & 4 - i \end{bmatrix} $.

### Exercise 12: Adjunct (Conjugate Transpose) of a Complex Matrix
Calculate the adjunct (or conjugate transpose) of the complex matrix 
$ m = \begin{bmatrix} 1 + 2i & 3 - i \\ 4 & 5 + i \end{bmatrix} $.

### Exercise 13: Checking the Dimensions of a Matrix
Determine the dimensions of the complex matrix 
$ m = \begin{bmatrix} 1 - i & 2 \\ 3 + 2i & 4 - i \end{bmatrix} $.

## Multiplication of Matrices and Vectors

### Exercise 14: Multiplying a Complex Square Matrix by a Complex Column Vector
Multiply the complex square matrix 
$ m = \begin{bmatrix} 1 + i & 2 - i \\ 3 & 4 + i \end{bmatrix} $ 
by the complex column vector 
$ v = \begin{bmatrix} 2 - i \\ 1 + 3i \end{bmatrix} $.

## Instructions
For each exercise, ensure to display both the input (vectors/matrices) and the result of the operation.Use NumPy for these exercises to practice handling complex numbers and matrix operations in Python.


In [14]:
import numpy as np


def exercise_1():
    print("Exercise 1: Sum of Two Complex Vectors")
    v1 = np.array([[1+2j], [3-1j]])
    v2 = np.array([[2-1j], [4+2j]])
    sum = v1 + v2
    print(f"v1 = [{v1[0][0]}]\n     [{v1[1][0]}]")
    print(f"v2 = [{v2[0][0]}]\n     [{v2[1][0]}]")
    print(f"sum = [{sum[0][0]}]\n        [{sum[1][0]}]\n")


def exercise_2():
    print("Exercise 2: Negation of a Complex Vector")
    v1 = np.array([[2 + 3j], [1 - 2j]])
    negation_v1 = -v1
    print(f"v1 = [{v1[0][0]}]\n     [{v1[1][0]}]")
    print(f"negation_v1 = [{negation_v1[0][0]}]\n         [{negation_v1[1][0]}]\n")


def exercise_3():
    print("Exercise 3: Multiplication of a Complex Vector by a Scalar")
    v1 = np.array([[1-1j], [2+2j]])
    scalar = 3+1j
    product = v1 * scalar
    print(f"v1 = [{v1[0][0]}]\n     [{v1[1][0]}]")
    print(f"scalar = {scalar}")
    print(f"product = [{product[0][0]}]\n          [{product[1][0]}]\n")


def exercise_4():
    print("Exercise 4: Transpose of a Complex Vector")
    v1 = np.array([[2-1j], [3+4j]]) 
    transpose_v1 = v1.T  
    print(f"v1 = [{v1[0][0]}]\n     [{v1[1][0]}]")
    print(f"transpose_v1 = [{transpose_v1[0][0]} {transpose_v1[0][1]}]\n")


def exercise_5():
    print("Exercise 5: Conjugate of a Complex Vector")
    v1 = np.array([[1+1j], [2-3j]])
    conjugate_v1 = np.conjugate(v1)
    print(f"v1 = [{v1[0][0]}]\n     [{v1[1][0]}]")
    print(f"conjugate_v1 = [{conjugate_v1[0][0]}]\n              [{conjugate_v1[1][0]}]\n")


def exercise_6():
    print("Exercise 6: Adjunct (Conjugate Transpose) of a Complex Vector")
    v1 = np.array([[1-2j], [3+1j]])  
    adjunct_v1 = v1.T.conj()  
    print(f"v1 = [{v1[0][0]}]\n     [{v1[1][0]}]")  
    print(f"adjunct_v1 = [{adjunct_v1[0][0]} {adjunct_v1[0][1]}]\n")


def exercise_7():
    print("Exercise 7: Sum of Two Complex Matrices")
    m1 = np.array([[1+1j, 2-1j], [3+2j, 4]]) 
    m2 = np.array([[2-3j, 1], [1j, 2+2j]])  
    sum_matrices = m1 + m2
    print(f"m1 = [{m1[0][0]} {m1[0][1]}]\n     [{m1[1][0]} {m1[1][1]}]")
    print(f"m2 = [{m2[0][0]} {m2[0][1]}]\n     [{m2[1][0]} {m2[1][1]}]")
    print(f"sum_matrices = [{sum_matrices[0][0]} {sum_matrices[0][1]}]\n            [{sum_matrices[1][0]} {sum_matrices[1][1]}]\n")


def exercise_8():
    print("Exercise 8: Negation of a Complex Matrix")
    m1 = np.array([[2+1j, 3], [1-1j, 2+2j]])
    negation_m1 = -m1
    print(f"m1 = [{m1[0][0]} {m1[0][1]}]\n     [{m1[1][0]} {m1[1][1]}]")
    print(f"negation_m1 = [{negation_m1[0][0]} {negation_m1[0][1]}]\n              [{negation_m1[1][0]} {negation_m1[1][1]}]\n")


def exercise_9():
    print("Exercise 9: Multiplication of a Complex Matrix by a Scalar")
    m1 = np.array([[1-1j, 2], [3+1j, 4-2j]])
    scalar = 2+3j
    product = m1 * scalar
    print(f"m1 = [{m1[0][0]} {m1[0][1]}]\n     [{m1[1][0]} {m1[1][1]}]")
    print(f"scalar = {scalar}")
    print(f"product = [{product[0][0]} {product[0][1]}]\n          [{product[1][0]} {product[1][1]}]\n")


def exercise_10():
    print("Exercise 10: Conjugate of a Complex Matrix")
    m1 = np.array([[1+1j, 2], [3-1j, 4+2j]])
    conjugate_m1 = np.conjugate(m1)
    print(f"m1 = [{m1[0][0]} {m1[0][1]}]\n     [{m1[1][0]} {m1[1][1]}]")
    print(f"conjugate_m1 = [{conjugate_m1[0][0]} {conjugate_m1[0][1]}]\n              [{conjugate_m1[1][0]} {conjugate_m1[1][1]}]\n")


def exercise_11():
    print("Exercise 11: Transpose of a Complex Matrix")
    m1 = np.array([[1-1j, 2+2j], [3, 4-1j]])
    transpose_m1 = m1.T
    print(f"m1 = [{m1[0][0]} {m1[0][1]}]\n     [{m1[1][0]} {m1[1][1]}]")
    print(f"transpose_m1 = [{transpose_m1[0][0]} {transpose_m1[0][1]}]\n              [{transpose_m1[1][0]} {transpose_m1[1][1]}]\n")


def exercise_12():
    print("Exercise 12: Adjunct (Conjugate Transpose) of a Complex Matrix")
    m1 = np.array([[1+2j, 3-1j], [4, 5+1j]])
    adjunct_m1 = m1.T.conj()
    print(f"m1 = [{m1[0][0]} {m1[0][1]}]\n     [{m1[1][0]} {m1[1][1]}]")
    print(f"adjunct_m1 = [{adjunct_m1[0][0]} {adjunct_m1[0][1]}]\n              [{adjunct_m1[1][0]} {adjunct_m1[1][1]}]\n")


def exercise_13():
    print("Exercise 13: Checking the Dimensions of a Matrix")
    m1 = np.array([[1-1j, 2], [3+2j, 4-1j]])
    dimension = m1.shape
    print(f"m1 = [{m1[0][0]} {m1[0][1]}]\n     [{m1[1][0]} {m1[1][1]}]")
    print(f"Dimension = {dimension[0]}X{dimension[1]}\n")


def exercise_14():
    print("Exercise 14: Multiplying a Complex Square Matrix by a Complex Column Vector")
    m1 = np.array([[1+1j, 2-1j], [3, 4+1j]])
    v1 = np.array([[2-1j], [1+3j]])
    product = np.dot(m1, v1)
    print(f"m1 = [{m1[0][0]} {m1[0][1]}]\n     [{m1[1][0]} {m1[1][1]}]")
    print(f"v1 = [{v1[0][0]}]\n     [{v1[1][0]}]")
    print(f"product = [{product[0][0]}]\n          [{product[1][0]}]")


def main():
    for i in range(1, 15):
        globals()[f'exercise_{i}']()


main()


Exercise 1: Sum of Two Complex Vectors
v1 = [(1+2j)]
     [(3-1j)]
v2 = [(2-1j)]
     [(4+2j)]
sum = [(3+1j)]
        [(7+1j)]

Exercise 2: Negation of a Complex Vector
v1 = [(2+3j)]
     [(1-2j)]
negation_v1 = [(-2-3j)]
         [(-1+2j)]

Exercise 3: Multiplication of a Complex Vector by a Scalar
v1 = [(1-1j)]
     [(2+2j)]
scalar = (3+1j)
product = [(4-2j)]
          [(4+8j)]

Exercise 4: Transpose of a Complex Vector
v1 = [(2-1j)]
     [(3+4j)]
transpose_v1 = [(2-1j) (3+4j)]

Exercise 5: Conjugate of a Complex Vector
v1 = [(1+1j)]
     [(2-3j)]
conjugate_v1 = [(1-1j)]
              [(2+3j)]

Exercise 6: Adjunct (Conjugate Transpose) of a Complex Vector
v1 = [(1-2j)]
     [(3+1j)]
adjunct_v1 = [(1+2j) (3-1j)]

Exercise 7: Sum of Two Complex Matrices
m1 = [(1+1j) (2-1j)]
     [(3+2j) (4+0j)]
m2 = [(2-3j) (1+0j)]
     [1j (2+2j)]
sum_matrices = [(3-2j) (3-1j)]
            [(3+3j) (6+2j)]

Exercise 8: Negation of a Complex Matrix
m1 = [(2+1j) (3+0j)]
     [(1-1j) (2+2j)]
negation_m1 = 